- js/PickerIOS.ios.js
A flow error is not noticed when RCTPicker is renamed to RNCPicker
> Fixed flow errors while RCTPicker is renamed to RNCPicker

- js/PickerAndroid.ios.js
- js/PickerIOS.android.js
On iOS there is an error in the console:
> ExceptionsManager.js:94 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check your code at PickerAndroid.ios.js:15.
> 
This is because a component instance is returned, not the component definition. 
This closes #38 
1. Have a demo iOS app with a Picker
1. Import the Picker as specified in the docs: 
`import {Picker} from '@react-native-community/picker';`
1. Launch an app on iOS where the Picker is imported. 
1. Turn on debugging and check the console.  …
> fix: react.createElement type is invalid

- README.md
We've been recommending devs use `npx pod-install` since it will attempt to install CocoaPods CLI if it's not available on the computer (cite [React Navigation setup guide](https://reactnavigation.org/docs/getting-started/#installing-dependencies-into-a-bare-react-native-project)).
This has proved very useful for Expo users who are now migrating to the bare workflow and want to use this package in their project.
> Use pod-install in setup instructions

- windows/ReactNativePicker/ReactNativePicker.vcxproj
- windows/ReactNativePicker/ReactPickerView.cpp
- windows/ReactNativePicker/pch.h
Some minor updates for Windows picker:
- Removed `XAML_NAMESPACE` macro in pch.h which caused some name collisions.
- Cleaned up project import paths.
Run the Windows test app as usual.
| Windows|    ✅     |
> Minor windows updates

- js/Picker.web.js
- js/PickerItem.js
Using `createElement` will apply RN StyleSheet styles properly and reset the styling. 
This also fixes the `testID` by mapping it to the attribute `data-testid`.
> [web] Use createElement for elements

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
This PR fixes several issues with items update on android:
1. Picker blinking
2. Reseting selection to first item and calling `onValueChange` with first value
**After:**
The problem was picker adapter was recreated every time items updated.
Potentially fixes #69
> fix: android: do not recreate picker adapter if items changed

- android/src/main/java/com/reactnativecommunity/picker/ReactDialogPickerManager.java
- android/src/main/java/com/reactnativecommunity/picker/ReactDropdownPickerManager.java
- example/android/app/build.gradle
- example/android/app/src/main/java/com/pickerexample/MainApplication.java
- example/android/settings.gradle
- js/AndroidDialogPickerNativeComponent.js
- js/PickerAndroid.android.js
This PR makes some addition to PR #99 
Since the example package previously relied on AndroidDialogPicker and AndroidDropdownPicker from the Core React Native Package, I've included the RNCPicker manually to the example, so that Android example actually uses the java code from this repository.
> fix: example to use its own code

- js/Picker.web.js
Fixes #97 
memoizing callbacks using `useMemo` causes the callback to be run on mount, which causes an error/
memoizing callback using `useCallback` fixes the error.
tested in example-web
> fix: target is undefined

- CHANGELOG.md
Fixes #81 
Removing Changelog.md in favor of https://github.com/react-native-community/react-native-picker/releases, since the changelog isn't being maintained
> chore: remove changelog in favor of releases

- js/PickerItem.js
As described in issue #113 the labels in Safari iOS are not displayed. The reason is that in PickerItem.js (line 23) the Option component is adding the label prop but unfortunately Safari iOS doesn't render the label. It appears to need the textContent of the option to properly render the label. 
So by adding the label as textContent the Safari case gets solved as well as for other browsers that don't support the label property.
```
<Option style={{color}} testID={testID} value={value} label={label}>
{label}
</Option>
```
The label is still passed as prop since the label values would default to textContent 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#Browser_compatibility
- [x ] I have tested this on a device and a simulator
> fix: Fix for Safari iOS labels not rendering

- js/Picker.web.js
- js/PickerItem.js
Since react-native-web 0.12, `createElement` was renamed to `unstable_createElement`.
Closes  issue #103
> fix: Fixed web with newer RN versions

- RNCPicker.podspec
The latest Xcode 12 fails to build when a module does not depend on `React-Core` directly. This change is necessary for all native modules on iOS. For details please see: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
1. Build an App with Xcode 11.x. Result: The app builds.
2. Build an App with Xcode 12. Result: The app will not build when depending on `React`.
3. Build an App with Xcode 12 with the PR changes applied. Result: The app builds.
Mac OS with Xcode 12
see Test Plan
| iOS     |    ✅     |
| Android |    ❌     |
> feat: Xcode 12 compatibility

- windows/ReactNativePicker/ReactNativePicker.vcxproj
Fix error produced when module is added to a React Native app and run in Windows emulator.
Error reads: "The target "Deploy" does not exist in the project".
> Resolve Missing Deploy Target

- .github/workflows/publish.yml
- README.md
- RNCPicker.podspec
- babel.config.js
- package.json
Migrating to `@react-native-picker` namespace to migrate out of react-native-community namespace, as stated in https://github.com/react-native-community/discussions-and-proposals/issues/176#issuecomment-693569246
> chore: migrate to new namespace

- package.json
- yarn.lock
updating detox package as it was causing error on yarn install with macos
Tested that detox test works with the latest version of detox
> chore: update detox

- README.md
- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- example/src/PickerExample.tsx
- js/PickerAndroid.android.js
- typings/Picker.d.ts
This pull request adds the possibility to set a color for dropdown arrow for Spinner component on Android.
Related issue is this: https://github.com/react-native-community/react-native-picker/issues/47
Add the property `dropdownIconColor='#ffffff'` for example, to see the updated color of arrow
| iOS     |    ❌     |
| Android |    ✅     |
> feat: Add a possibility to change the color of dropdown icon

- package.json
- yarn.lock
cleaned up yarn.lock, reducing size of node_modules from 1.2GB to 900MB
> chore: clean node modules

- js/PickerAndroid.android.js
This PR fixes bug on Android when Picker.Item is null, but its index is taken into account
> fix: [Android] fixed index with null child

- typings/Picker.d.ts
This PR fixes the typescript definition of Picker.Item to conform with the implementation.
> fix: Adjust typing of Picker.Item to conform with implementation #176

- js/PickerMacOS.macos.js
- macos/RNCPicker.h
- macos/RNCPicker.m
This fixes #185 
1. Fixes compilation on macOS the _font property was overwriting some other inherited property and that was causing troubles
2. Fixes the height to be closer to the native component real height, otherwise rendering is very broken
> fix: Fix compilation and rendering on macOS

- ios/RNCPicker.m
Unfortunately I missed one line of code in my previous PR.
- set accessibilityIdentifier to testID manually for each item in the Objective-C code.
> fix: add accessibilityIdentifier to testID

- js/PickerMacOS.macos.js
- macos/RNCPicker.m
As mentioned on #187, the macOS picker was not correctly setting the correct index when passed a value, the internal method was calling itself instead of the NSPopUp method for setting the selected index
Also fixes the height a bit to correctly show the entire picker box
> fix: Fix macOS picker not correctly setting controlled value

- typings/Picker.d.ts
* Use literal type to avoid typescript warning while assigning `mode` prop of Picker using the static constant: `mode={Picker.MODE_DIALOG}`
* Fix android default picker mode comment for intellisense
> fix: picker declaration

- js/PickerAndroid.js
- js/PickerIOS.js
- js/PickerItem.js
- js/PickerMacOS.js
- js/PickerWindows.js
- js/PickerWindows.windows.js
replaced the import for UnimplementedView which is no longer exported from `index.js` of react-native
> fix: replace UnimplementedView import

- typings/Picker.d.ts
onValueChange gives me a Typescript error:
```
Overload 1 of 2, '(props: Readonly<PickerProps>): Picker', gave the following error.
Type '(value: string) => void' is not assignable to type '(itemValue: string | number, itemIndex: number) => void'.
Types of parameters 'value' and 'itemValue' are incompatible.
Type 'string | number' is not assignable to type 'string'.
```
This is due to enforcing that value is of type `ItemValue` which could be both number and string.  (In my case value is supposed to be a string, not a number.)
This way Typescript should pick up on the type of `selectedValue` to determine whether `value` in `onValueChange` is number or string
> fix: Update Picker.d.ts

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- js/PickerAndroid.android.js
fixes crash on Android when using string variables for dropdownIconColor
> fix: allow variables for dropdownIconColor

- README.md
- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- example/src/PickerExample.tsx
- js/AndroidDialogPickerNativeComponent.js
- js/AndroidDropdownPickerNativeComponent.js
- js/PickerAndroid.android.js
- js/types.js
- typings/Picker.d.ts
fix #207 fix #126 
Add `enabled` property to `Picker.Item` that will allow users to disable individual items on android
> feat: disable picker item

- android/src/main/java/com/reactnativecommunity/picker/ReactPicker.java
- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- example/android/app/src/main/AndroidManifest.xml
- example/src/App.tsx
Hi, I added rtl support for android picker. To test that you can open example app and toggle switch which will trigger `I18nManager.forceRTL` method, after that app needs to be reloaded (neither state change, nor fast refresh does not work).
Closes #218
> feat: implement rtl support for android picker

- typings/index.d.ts
Hi! Thanks for writing this library. This PR exposes the `PickerProps` and `PickerItemProps` from the main package export.
This allows importing the types like this:
```ts
import { PickerProps } from "@react-native-picker/picker";
```
Instead of:
```ts
import { PickerProps } from "@react-native-picker/picker/typings/Picker";
```
> chore: export props from index

- README.md
- js/PickerAndroid.android.js
- typings/Picker.d.ts
Adds mention about android focus functionalities being available from 1.16.0 (Closes #279 - which is follow up to discussion under https://github.com/react-native-picker/picker/pull/258#issuecomment-860212262 comment)
Adds focus typescript types
Removes legacy ref usage from android picker
> fix: Focus and ref fixes

- typings/Picker.d.ts
- typings/PickerIOS.d.ts
- typings/index.d.ts
After updating to the v1.16.3 release I got the following typescript issues in my project:
```
$ tsc
node_modules/@react-native-picker/picker/typings/Picker.d.ts:92:18 - error TS2304: Cannot find name 'NativeSyntheticEvent'.
92    onFocus?: (e: NativeSyntheticEvent<TargetedEvent>) => void
~~~~~~~~~~~~~~~~~~~~
node_modules/@react-native-picker/picker/typings/Picker.d.ts:92:39 - error TS2304: Cannot find name 'TargetedEvent'.
92    onFocus?: (e: NativeSyntheticEvent<TargetedEvent>) => void
~~~~~~~~~~~~~
node_modules/@react-native-picker/picker/typings/Picker.d.ts:97:17 - error TS2304: Cannot find name 'NativeSyntheticEvent'.
97    onBlur?: (e: NativeSyntheticEvent<TargetedEvent>) => void
~~~~~~~~~~~~~~~~~~~~
node_modules/@react-native-picker/picker/typings/Picker.d.ts:97:38 - error TS2304: …
```
> fix: Fix typings by importing missing NativeSyntheticEvent and TargetedEvent

- typings/Picker.d.ts
Made `PickerItemProps` accept a generic `T` so that pickers are typed so they can hold data other than `ItemValue`
If this typing decision was intentional, feel free to close this PR :)
> make PickerItemProps accept generic value rather than just ItemValue

- README.md
- android/gradle.properties
- android/src/main/java/com/reactnativecommunity/picker/ReactPicker.java
- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- android/src/main/res/drawable/ic_dropdown.xml
- android/src/main/res/drawable/spinner_dropdown_background.xml
- example/src/PickerExample.tsx
- js/PickerAndroid.android.js
- typings/Picker.d.ts
closes #266
closes #235
closes #112
In order to fix issues with buggy color/style changes to android spinner's background
I created custom background resource which should look identical to default one
It allowed to finally have proper color/background change possibilities.
With default background, if one had applied custom backgroundColor in JS,
it overriden whole background for spinner, which resulted in removing
dropdown icon completely.
With new custom background resource, we can apply color changes directly to
icon or spinner background.
As a side-effect, I introduced possibility to change icon ripple color also,
it is exposed as dropdownIconRippleColor prop
**NOTE**: minSdkVersion was increased to 21 (now it matches with react-native core)
> fix(android): spinner background issues

- android/build.gradle
- android/gradle.properties
The purpose of this PR is to fix the bellow error:
<details>
<summary>Stack Trace</summary>
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-picker_picker:packageDebugResources'.
> Error: 6 exceptions were raised by workers:
java.lang.RuntimeException: java.lang.RuntimeException: Error while processing /Users/reberthkelvin/Projects/Delfos/delfos_im/DelfosimApp/node_modules/@react-native-picker/picker/android/src/main/res/drawable/ic_dropdown.xml : Can't process attribute android:fillColor="@android:color/black": references to other resources are not supported by build-time PNG generation.
File was preprocessed as vector drawable support was added in Android 5.0 (API level 21)
See …
```
> fix: Android min sdk 16 compatibility

- js/Picker.web.js
- js/PickerAndroid.js
- js/PickerAndroid.web.js
- js/PickerIOS.js
- js/PickerIOS.web.js
- js/PickerItem.js
- js/PickerMacOS.js
- js/PickerMacOS.web.js
- js/PickerWindows.js
- js/PickerWindows.web.js
- js/UnimplementedView.js
- tsconfig.json
Fix #238 
Added UnimplementedView and changed way of importing createElement for web so that picker can be used on web without needing to strip flow code
> fix: Build Web without Flowtype

- js/UnimplementedView.web.js
fixes #100 fixes #134
Fix Unimplemented View so that it can be imported from create-react-app project without modifying webpack
> fix: unimplemented view export

- README.md
- example/ios/PickerExample.xcodeproj/project.pbxproj
- example/ios/Podfile.lock
- ios/RNCPicker.h
- ios/RNCPicker.m
- ios/RNCPicker.xcodeproj/project.pbxproj
- ios/RNCPickerLabel.h
- ios/RNCPickerLabel.m
- ios/RNCPickerManager.m
- js/PickerIOS.ios.js
- js/RNCPickerNativeComponent.js
- typings/Picker.d.ts
- typings/PickerIOS.d.ts
Add multiline support for iOS picker. `numberOfLines` prop on iOS accepts integer value greater or equal to 1.
Picker rows' height is based on that prop.
**NOTE** in order to prevent multiline text being cut on leading and trailing edges on iOS 14, there is hardcoded horizontal padding of 20pts added to UILabel (Closes #212), potentially in future, it can be adjusted via `style` or `itemStyle` props
> feat: numberOfLines prop on iOS

- js/Picker.web.js
- js/PickerItem.js
The dynamic imports in the web part are causing issues together with `react-native-web`, `electron` and `vite` as bundler.
With a proper configuration, electron disallows the `require` statement, and it's very tricky to solve this require errors with `vite`. It's better to use `import`.
> fix: Fixed dynamic imports of react-native-web

- js/Picker.web.js
- js/PickerItem.js
Remove createElement usage & use `unstable_createElement` in web instead [as it has been renamed in react-native-web v0.12.0](https://github.com/necolas/react-native-web/releases/tag/0.12.0)
Resolve #355
Tested by running example in web, as I'm only changing the web part
> BREAKING CHANGE: remove createElement usage in react-native-web

- js/Picker.web.js
A few changes on `forwardedRef` allows anyone to pass a React `ref`on Web version and get a ref of `<select>` tag that renders `Picker`. I am currently using a forked version with these changes in order to get `focus( )` method of `<select>` tag and avoid dirty code. 
Let me know guys what do you think. I am fully available to make any changes neccesary.
> fix: add ref support for Web

- js/Picker.web.js
Importing with a `*` may have some issues with Web's tree shaking. This minor PR edits the import to import `unstable_createElement` directly to avoid any potential tree shaking issues.
> chore: Optimize for web tree shaking

- windows/ReactNativePicker/ReactPickerView.cpp
- windows/ReactNativePicker/ReactPickerView.h
Currently picker does not support darkMode (at least in our XamlIsland based app).
This issues seems to be identical to: https://github.com/microsoft/microsoft-ui-xaml/issues/2331.
The solution is based of https://github.com/microsoft/react-native-windows/pull/8777/files
.
Before:
After
> fix: Workaround XAML bug with ComboBox and dark theme

- js/PickerWindows.windows.js
This partially fixes #310, for Windows only.
Tested locally with the app that I'm building - the React Native Windows framework handles the accessibility label properly, but it was not originally passed through props.
Let me know if I'm missing anything!
> fix: Fixing accessibility label on Windows.

- windows/ReactNativePicker/ReactNativePicker.rc
- windows/ReactNativePicker/ReactNativePicker.vcxproj
- windows/ReactNativePicker/Reactnativepicker.vcxproj.filters
- windows/ReactNativePicker/resource.h
Addresses the following issue:
https://github.com/react-native-picker/picker/issues/443
> fix: Add DLL file information resource file to ReactNativePicker windows

- js/PickerAndroid.android.js
Fixes an issue where `backgroundColor` is not passed to the `Item` object without `color` being passed through `style` prop
> fix: Item backgroundColor fix

- README.md
- example/src/PickerIOSExample.tsx
- ios/RNCPicker.h
- ios/RNCPicker.m
- ios/RNCPickerManager.m
- js/PickerIOS.ios.js
- js/RNCPickerNativeComponent.js
- typings/Picker.d.ts
This PR addresses #294 by adding an iOS only property called `selectionColor`, which is then set to the proper sub-view of the UIPicker.  The example project & docs have also been updated.
❓ My purposes for completing work on this functionality were to make the selection transparent so that I could show two pickers side by side with one a single selection indictor rendered in JS.  In using the `transparent` color, I noticed the indicator still shows up, but I know that `transparent` is equal to `#00000000` which seemingly should be the same as `#FFFFFF00` but it's not... using the later gave me what I wanted.
The question being, would you like for me to account for this in the JS or let the user deal with it if they happen find it?  I can easily make a single line that translates …
> fix: Issue 294 - selection color

- windows/ReactNativePicker/ReactNativePicker.vcxproj
Bump WindowsTargetPlatformMinVersion. New version needed in order to support usage on WinUI 2.8 in apps.
> fix: Bump WindowsTargetPlatformMinVersion 

- windows/ReactNativePicker/ReactNativePicker.vcxproj
Fix SDK build error if 10.0.18362.0 is not installed:
```
× Building Solution: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft...
× Build failed with message C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.18362.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution".
```
See https://github.com/react-native-async-storage/async-storage/pull/810 for a similar fix.
Previously, after bringing down package dependencies you'd have to retarget the SDK version for the module project.
Committed to a fork and …
> Remove explicit SDK version for Windows builds

- README.md
In the README.md, the section about Expo SDK 37 seems irrelevant as its pretty old and the SDK version is no longer supported by the Expo team. Currently, the SDK versions supported are [46 to 49](https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a-react-native-version).
This PR removes the section about managed Expo SDK 47.
> (docs): Remove outdated Expo SDK version and related info

- .flowconfig
- js/AndroidDropdownPickerNativeComponent.js
- js/Picker.js
- js/Picker.web.js
- js/PickerIOS.ios.js
- js/PickerMacOS.macos.js
- js/RNCPickerNativeComponent.js
- package.json
- yarn.lock
update flow version with temporary workaround
> fix: update flow version

- js/PickerWindows.windows.js
- windows/ReactNativePicker/ReactPickerView.cpp
- Platform: Windows
- "@react-native-picker/picker": "^2.4.8"
- "react-native": "<=0.67.2"
Currently, when attempting to set the testID property on Picker Items, it does not function as expected on Windows platforms.
> Fix: Add TestID for PickerWindows

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerLocalData.java
- android/src/main/java/com/reactnativecommunity/picker/ReactPickerShadowNode.java
Closes #555
Closes #556 
Closes #557
Revert `ReactPickerLocalData` back to a normal java class. 
Tested on 0.71, 0.72, 0.73, and 0.74
> fix: revert change to java record

- windows/ReactNativePicker/ReactNativePicker.vcxproj
Remove the block that verifies that NuGet packages have been downloaded. Since RNW 0.68, this causes build failures because RNW manages dependencies using package references.
> fix(windows): update VS project to support package refs

- android/build.gradle
having the error when building on android with new architecture enabled and in a monorepo:
```
* What went wrong:
A problem occurred evaluating project ':react-native-picker_picker'.
> [react-native-picker] Unable to resolve react-native location in node_modules. You should add project extension property (in app/build.gradle) `REACT_NATIVE_NODE_MODULES_DIR` with path to react-native.
```
the line should be referenced from other libraries but since the current npm package name is namespaced under `@react-native-picker/picker`, we should add more ".."
```bash
#!/bin/bash
mkdir RN074Monorepo
cd RN074Monorepo
cat > package.json <<EOF
{
"private": true,
"workspaces": ["apps/*"]
}
EOF
mkdir apps
cd apps
npx @react-native-community/cli@latest init RN074 --version 0.74.0-rc.7 --skip-install
cd …
```
> fix(android): build error on monorepo

- ios/RNCPicker.mm
- ios/RNCPickerComponentView.mm
Selecting an item with an empty value crashes the app because we convert an empty string to null,
https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/ios/RNCPickerComponentView.mm#L51
and it crashes here.
https://github.com/react-native-picker/picker/blob/7b7a95f4fe842d0a0c696310f9f10a8267247227/ios/RNCPicker.mm#L160
1. Run the example app with `RCT_NEW_ARCH_ENABLED` enabled
2. Add a picker item with an empty value to the example
3. Scroll the picker to select the item with an empty value
> [Fabric] [iOS] Fix app crash when selecting an empty value

- FabricExample/package.json
- FabricExample/yarn.lock
- android/src/main/java/com/reactnativecommunity/picker/ReactPicker.java
The check of `getReactContext().hasCatalystInstance()`  inside `onMeasure` will return true on both architectures so it needs to be changed. Replaced it with `BuildConfig.IS_NEW_ARCHITECTURE_ENABLED`. Also updated the example to use the latest stable RN.
> fix: Change method of detecting the new arch

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
`receiveCommand(@NonNull ReactPicker root, int commandId, @androidx.annotation.Nullable ReadableArray args)` 
for INT was deprecated 5 years ago in favour of 
`receiveCommand(@NonNull ReactPicker root, String commandId, @androidx.annotation.Nullable ReadableArray args)`
This is needed to get rid of `dispatchCommand` INT variant here : https://github.com/facebook/react-native/blob/044aadbaf6830b21aab821804dc5a7989010022e/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/UIManagerModule.java#L591-L595
The usages in [@react-native-picker/picker](https://github.com/react-native-picker/picker/) are [all](https://github.com/search?q=repo%3Areact-native-picker%2Fpicker%20receiveCommand&type=code) dependent on String variant
> Delete deprecated receiveCommand for INT

- js/PickerAndroid.android.js
In some cases, children are not available yet or props are undefined in Android which causes the app to crash
> fix: resolve android crash issue if props are undefined

- ios/RNCPicker.mm
- js/PickerIOS.ios.js
This PR adds missing accessibilityLabel and accessibilityHint props on iOS Picker component. The solution uses UIPickerViewAccessibilityDelegate which uses values from accessibilityLabel and accessibilityHint JS props.
closes #310 
Attaching two recordings, one before fix and one after fix.
By default VoiceOver announces the text of selected picker item, then it announces "picker item", then it announces "adjustable" accessibilityRole, then it announces item's position in collection, e.g. 1 of 3. After that it announces default hint for swiping picker up or down to change selected item.
After fix, Voiceover will first announce the accessibilityLabel value, then the text of selected picker item, then it announces "picker item", then it announces "adjustable" accessibilityRole, then it …
> fix(#310): missing a11y label and hint props on iOS Picker

- android/src/main/jni/CMakeLists.txt
Due to the introduction of `libreactnative.so` in 0.76 we must update the `CMakeLists.txt
` file to be compatible with merged libraries, more details can be found at https://github.com/react-native-community/discussions-and-proposals/discussions/816
This PR can be tested through the update of the FabricExample, here -> https://github.com/react-native-picker/picker/pull/587
> feat: Add support for react-native 0.76.0

- FabricExample/Gemfile
- FabricExample/android/app/build.gradle
- FabricExample/android/app/src/main/java/com/fabricexample/MainApplication.kt
- FabricExample/android/build.gradle
- FabricExample/android/gradle/wrapper/gradle-wrapper.properties
- FabricExample/android/settings.gradle
- FabricExample/ios/FabricExample.xcodeproj/project.pbxproj
- FabricExample/ios/FabricExample/PrivacyInfo.xcprivacy
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
React Native 0.76.0 is officially out and in order to add proper support for it we should be able to test it in the latest version
Upgrade FabricExample project based on [upgrade-helper](https://react-native-community.github.io/upgrade-helper/?from=0.74.1&to=0.76.0)
> chore(FabricExample): update React Native version to 0.76.0

- README.md
Currently, the previews are in one line and are not visible, unless zoomed in or clicked on. This way can add extra steps to view one simple image
before:
after:
> 📝 Update README.md to make previews more visible

- typings/Picker.d.ts
Allows to set a Picker Item value to an object and be able to do something with the selected itemValue on the onValueChange callback function
> fix: Adds object as a type on type ItemValue

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
Support deprecated receiveCommand which receives commandId as int.
It may be RN bug and also dependent on RN version, but running on RN 0.76.2 (old arch), the `receiveCommand` which accepts `String commandId` is never called, therefore calling `focus()` and `blur()` functions does nothing. Here we manually delegate this call using the deprecated `receiveCommand`. JS sends the command id as Int.
> fix: Add deprecated receiveCommand method

- ios/RNCPicker.mm
- ios/RNCPickerComponentView.mm
- ios/RNCPickerFabricConversions.h
- js/PickerIOS.ios.js
- js/RNCPickerNativeComponent.js
PR fixing regression with string values instead of numeric ones from https://github.com/react-native-picker/picker/pull/456 requested in https://github.com/react-native-picker/picker/issues/538
> fix: use dynamics to cover string and number

- js/PickerAndroid.android.js
While working on a simple task in my React Native Expo application, I encountered an issue when using a picker component. The error was observed on my Android device during runtime.
**Problem**
The error message suggested a potential issue with null or undefined values being passed to the picker. After investigating further, I discovered that the value prop for some Picker.Item components was not being validated properly in this case if an empty string was passed. Causing the application to crash in specific scenarios.
**Code Snippet**
```
<View style={styles.dropdownContainer}>
<Text style={styles.label}>City / Region</Text>
<Picker
selectedValue={city}
style={styles.picker}
onValueChange={(itemValue) => {
setCity(itemValue);
setArea("");
}}
>
<Picker.Item label="Select City" value="" /> …
```
> Fix: Prevent 'TypeError: Cannot read property 'value' of undefined' in Picker Component

- android/src/paper/java/com/facebook/react/viewmanagers/RNCAndroidDialogPickerManagerDelegate.java
- android/src/paper/java/com/facebook/react/viewmanagers/RNCAndroidDropdownPickerManagerDelegate.java
needed to support RN 77 because of https://github.com/facebook/react-native/pull/46809
this only influences old architecture, not new
tested locally
> feat: support RN 0.77

- package.json
Hello! 👋
This PR addresses an issue where, on iOS with React Native >= 0.77:
- Picker items display as question marks (?)
- Items cannot be selected
closes #631 
closes #612
closes #625
Reference: [react-native-picker/picker#612](https://github.com/react-native-picker/picker/issues/612)
⚠️ I haven't had the chance to test for backward compatibility.
I'm also not deeply familiar with the codebase, so please feel free to adjust or reject as needed.
Thanks!
> fix(ios): question marks rendered unexpectedly (RN >= 0.77)

- android/src/main/jni/RNCAndroidDialogPickerMeasurementsManager.h
- android/src/main/jni/RNCAndroidDropdownPickerMeasurementsManager.h
Using `ContextContainer::Shared` is deprecated, and is making the build against `react-native@nightly` failed because of a C++ warning.
> Do not use deprecated `ContextContainer::Shared`
