react-native-picker/picker

- android/gradle.properties
- android/src/main/java/com/reactnativecommunity/picker/ReactPicker.java
- example/android/app/build.gradle
- example/android/gradle.properties
> migrate-to-androidx

- README.md
the url for react-native document has changed to `reactnative.dev` 
This PR reflects the url update.
> docs: update react-native docs url

- README.md
Added supported version of RN in README.
From version `1.2.0`, RN version needs to be >0.59 since this it has supports for androidx
> docs: add supported version in README

- typings/Picker.d.ts
- typings/PickerIOS.d.ts
Fix the TypeScript typings. They were unusably broken in a number of ways.
> Fix TS typings

- CHANGELOG.md
this PR fix links in CHANGELOG.md when you click this links appears 404 error.
> fix links in CHANGELOG.md

- js/PickerWindows.windows.js
> [windows] Remove unused code

- js/Picker.web.js
prevent extra updates by wrapping handleChange in a memo hook.
> [web] memoize handleChange

- ios/RNCPicker.m
Sets the dataSource property on iOS. Only an internal change, doesn't change behaviour or the API. Requirement for [this Detox issue](https://github.com/wix/Detox/issues/2031). Fixes #74 
Just test it still works
None
| iOS     |    ✅     |
| Android |    ✅     |
Not sure if this needs to be mentioned in the changelog
> fix: Set dataSoure property

- android/src/main/java/com/reactnativecommunity/picker/ReactDialogPickerManager.java
- android/src/main/java/com/reactnativecommunity/picker/ReactDropdownPickerManager.java
- js/PickerAndroid.android.js
> rename android pickers to reduce naming conflicts

- README.md
Hello, Hi!
I spent some time implementing this library into my project that was using the managed workflow from expo 37, to discover that it does not work on iOS. I think adding a small blurb in the readMe would help others avoid this issue.
> Updated ReadMe to include note that this library does not work with a managed workflow using Expo 37

- .github/workflows/publish.yml
change env to fix publish action
> fix: publish action

- js/Picker.web.js
Fix #145 Fix Picker component for web to clear warning for forwardRef
> fix: clear warning for picker web

- js/PickerIOS.ios.js
> fix: Add testID to PickerIOSItemType

- .github/workflows/ci.yml
- example/macos/PickerExample-iOS/AppDelegate.m
- example/macos/PickerExample-macOS/Base.lproj/Main.storyboard
- example/macos/PickerExample-macOS/ViewController.m
- example/macos/PickerExample.xcodeproj/project.pbxproj
- example/macos/Podfile
- example/macos/Podfile.lock
fix MacOS example so that pod install can run normally
> chore: fix MacOS Example

- .github/workflows/publish.yml
rename CI step to correctly display what's being done
> chore: rename CI step

- package.json
- yarn.lock
update semantic release package to allow auto release
> chore: update semantic release

- js/PickerIOS.js
> fix: unable to resolve module import on android

- js/PickerIOS.ios.js
- js/PickerMacOS.macos.js
- js/RNCPickerNativeComponent.js
This fixes issue 180 https://github.com/react-native-picker/picker/issues/180
> fix: issue-180

- example/ios/Podfile.lock
- example/src/App.tsx
- example/src/PickerExample.tsx
> chore: update example

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- js/PickerAndroid.android.js
- typings/Picker.d.ts
Credits for the fix to @billnbell
> fix:Fix to font family

- example/src/PickerExample.tsx
- js/Picker.js
- js/__tests__/Picker.test.js
- js/__tests__/__snapshots__/Picker.test.js.snap
- typings/Picker.d.ts
Add accessibility Label prop
Talk back speaks out set accessibility label
> feat: add accessibility Label props

- js/AndroidDropdownPickerNativeComponent.js
- js/PickerAndroid.android.js
Refactored PickerAndroid to use Function Component
> feat: use function component

- android/src/main/java/com/reactnativecommunity/picker/ReactPickerManager.java
- example/src/PickerExample.tsx
- js/AndroidDialogPickerNativeComponent.js
- js/AndroidDropdownPickerNativeComponent.js
- js/PickerAndroid.android.js
- typings/Picker.d.ts
fix #73 fix #173 fix #166
Added style for individual picker items in android
> feat: add item styles for android

- android/src/main/java/com/reactnativecommunity/picker/PickerBlurEvent.java
- android/src/main/java/com/reactnativecommunity/picker/PickerFocusEvent.java
> fix(#281): incompatibility with RN 0.65+

- typings/Picker.d.ts
> fix(#313): incorrect color types

- example/src/PickerExample.tsx
- example/src/__tests__/PickerExample.test.tsx
- package.json
- yarn.lock
@testing_library/react_native is quite a popular testing library. This test shows how to test implementations of the picker.
(It would have saved me some time ;))
> docs: Adds a unittest for the example using @testing_library/react_native

- example/src/PickerWindowsExamples.js
- js/Picker.js
- js/PickerIOS.ios.js
> chore: fix lint ci

- android/build.gradle
> fix: add mavenCentral to build script

- .github/workflows/ci.yml
- .github/workflows/publish.yml
fix publish ci so that new release will be created
> Fix Publish CI

- .github/workflows/ci.yml
- .github/workflows/publish.yml
> build: update node version for ci

- yarn.lock
clean up babel dependencies to reduce node_modules size
> build: clean up babel dependencies

- ios/RNCPickerComponentView.mm
We at [Software Mansion](https://swmansion.com/) have been working on [improving support](https://blog.swmansion.com/sunrising-new-architecture-in-the-new-expensify-app-729d237a02f5) for the new architecture for quite a while now. If you need help with anything related to New Architecture, like:
- [migrating your library](https://x.com/swmansion/status/1717512089323864275)
- [migrating your app](https://github.com/Expensify/App/pull/13767)
- [investigating issues](https://github.com/facebook/react-native/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3Aj-piasecki+is%3Aopen)
- [improving performance](https://x.com/BBloniarz_/status/1808138585528303977)
or you just want to ask any questions, hit us up on [projects@swmansion.com](mailto:projects@swmansion.com)
---
PR adding `load` method needed …
> feat: add load method

- .github/workflows/ci.yml
- .github/workflows/publish.yml
motivation: https://github.com/react-native-picker/picker/actions/runs/15773781562/job/44463570579
> chore: update publish workflow
